### PR TITLE
Don't update killer moves if is Enpassant

### PR DESCRIPTION
**Pull request by TheDarkKnightRise**

### CODE REVIEW

**Comment by PGG106** [comment]
Refer to the contribution guidelines, any change that affects search or eval has to go through SPRT, there's no point in opening a PR for every change you can think of since most will fail SPRT, SPRT the change first and only if it passes open a PR (with the SPRT results in it)

**Comment by TheDarkKnightRise** [comment]
**This is completely true pull , you ignore it !!!**

_Unfortunately, I can no longer contribute with you , you close my pull without true reason_ 

the day will come when this pull will be merged by yourself

Best of luck to you dear friend. Good bye

**Comment by PGG106** [comment]
i suggest looking into how a chess engine is developed and looking into what a SPRT is and why every single engine uses it to filter patches. The idea that you can simply pr a search patch with no test done beforehand is ridicolous and doesn't only go against the very own contribution guidelines of the repo you are trying to contribute to but common sense.
PS: i didn't ignore it, it wasn't approriate and i closed it, that's a lot different than ignoring

**Comment by TheDarkKnightRise** [comment]
https://user-images.githubusercontent.com/121218340/213583247-39805479-88d2-4852-836f-bb6832e2a4e0.mp4

**Comment by PGG106** [comment]
This pull request didn't respect the contribution guidelines, any change to search or eval has to be sprt-ed and any engine developer will know and tell you this. 
ny pr that doesn't respect the contribution guidelines will be closed, any other PR you open that doesn't respect the contribution guidelines will get you banned, this isn't up for debate.
If you somehow believe that SPRT isn't needed when developing an engine alexandria is  released under gpl3, this means you can make your own derivative and release as long as you respect the gpl license, but don't expect changes that explicitely go against the guidelines to be merged.

**Comment by PGG106** [comment]
The idea is that a patch gets tested before opening a PR and the PR gets opened only after passing the test (there's no need to open 10000 patches and getting only 50 merged in because the others failed sprt).
 I encourage you to sprt your own ideas, the guidelines do state "i'll judge whether i can spare the resources to run it" but i can tell you already i'm currently short on resources so there's no way i can run other people patches.

**Comment by PGG106** [comment]
i saw the code, it changes search behaviour, it needs a SPRT, that's how it works

**Comment by PGG106** [comment]
not really, the definition isn't that strict, some engines consider en passant to be quiet because it's a pain in the ass to exclude it and in my case promotions are never quiet (even when not capturing a piece).
No matter how small or seemingly irrelevant a search/eval change is, it has to be tested and the only good way to test it is sprt, there's no other way around it and no argument that will change this.

**Comment by PGG106** [comment]
it's the same with #108, you opened an "optimization" PR and didn't even bother checking if the actual measured speed went up or not (and if you did you didn't report any of that), that's not the best way to contribute and you can definitely imrpove on this.

**Comment by PGG106** [comment]
> **Enpassant** is a capture move & Should not update killer move when we have a capture move

sure, this might even be considered a minor "bug", problem is even fixing "bugs" like this one can make you lose elo (engines are weird), this mean that any, and i repeat for the last time, any change to search or eval has to be tested, there's no other way around it and no argument that will change this.

**Comment by PGG106** [comment]
fwiw i knew about this behaviour since for a long time en passant was flagged as a capture, when i removed that i checked that it didn't break anything, an sprt of this change would end up failing and that's the reason why i'm not wasting my resources to run it.

**Comment by PGG106** [comment]
i explained to you why that's not the case 10 times already, i will not explain it an 11th time, consider yourself warned

**Comment by PGG106** [comment]
your point is "i refuse to follow the contribution guidelines and i will spam other wrong PRs in the future", banned.

**Pull request closed without merging**
