### PR TITLE
Add heavy position for bench test

### PR DESCRIPTION
**Pull request by TheDarkKnightRise**

### CODE REVIEW

**Comment by PGG106** [comment]
The positions in bench aren't really relevant, bench is only used to get a unique signature (in the form of the number of nodes) for a specific version of the engine, as it stands this change would only make bench take longer for no good reason.

**Comment by TheDarkKnightRise** [comment]
Not problem , I said before i have conversation with you in next pull , can i ask a question ?

**Comment by PGG106** [comment]
sure, note that i have formalized a draft of the contribution guidelines and added them to the readme to make it more clear how to contribute to the engine

**Comment by TheDarkKnightRise** [comment]
Why hide me from contributors name ?

image

**Comment by PGG106** [comment]
that's a problem on the github side of things i have no input on, my best guess is it takes some days for it to update

**Comment by PGG106** [comment]
image
you show up just fine on my end, try clearing cache (?) , as i said it's not something i have any control over

**Comment by TheDarkKnightRise** [comment]
image

not cached , this is my screenshot yesterday , your engine is good but Honesty is best

**Comment by PGG106** [comment]
don't know what to tell you, it's not something i can change at all and by spamming F5 on the main repo page your icon appears and disappears for reasons beyond my understanding, i'd suggest you doing the same to see that for yourself, you also show up just fine in the contributors page so github clearly knows you are one

**Comment by TheDarkKnightRise** [comment]
If you had merged my pull, this problem would have been solved

> the intended syntax is go perft <depth> and this makes it possible to input strings that violate those rules
> 
> _Originally posted by PGG106 in https://github.com/PGG106/Alexandria/issues/100#issuecomment-1384560924_

Which rules does this change violate? 

I honestly want to help you, but I can't do anything until this problem is solved

**Comment by PGG106** [comment]
"else if (input.find("perft") != std::string::npos) {" evaluates as true even for strings such as "perft 7", the command has to be "go perft 7", the current setup works because the program won't enter the parse go function if there isn't a go in the input, your change broke that therefore the PR wasn't approved.

**Comment by PGG106** [comment]
also for future issues like this be sure to read up on the updated contributions guidelines, this wouldn't have happend and shouldn't happen again if you first open an issue.

**Comment by TheDarkKnightRise** [comment]
there is no rule  as `go perft 7` , only Stockfish use it !

other chess engine use `perft 7` comment  , for example you can see crafty engine :

https://github.com/MichaelB7/Crafty

**Comment by PGG106** [comment]
that's the internal rule that was in use with the code you changed, it's also the internal rule the engine abides to, i don't care what other engines do, the current accepted syntax to run perft in alexandria is "go perft <depth>".

**Comment by TheDarkKnightRise** [comment]
I know your engine rules is the base of stockfish rules 
I had a new pull base of stockfish
 I don't think this violate  rules https://github.com/PGG106/Alexandria/pull/104

**Pull request closed without merging**
