### PR TITLE
Fix Bug "Unknown command"

### PR DESCRIPTION
**Pull request by TheDarkKnightRise**
```
Unknown command: go depth 10

Unknown command: position fen 2r3k1/B5pp/2r1p3/1q1n4/2p2P2/P5P1/1PR1Q2P/1KR5 b - - 0 36
```

### CODE REVIEW

**Comment by TheDarkKnightRise** [comment]
i did this pull , why do this single ???

**Comment by PGG106** [comment]
by the time i noticed the PR i had already written and pushed a fix, basically when i read the perft PR i tested the problem and also noticed this one so i went and fixed it (without knowing you were working on a fix already), the perft PR i saw in time but i preferred a different approach for the solution and i figured that instead of spoonfeeding it to you via reviews and request for changes i could just commit it myself

**Comment by PGG106** [comment]
In the future open an issue so i can tell you if i'm already working on it or give you the ok to fix the problem and open a PR, thank you

**Comment by PGG106** [comment]
i've added you as a co-author to mitigate the situation

**Pull request closed without merging**
