### PR TITLE
Adding Alexandria Classic Eval 

### PR DESCRIPTION
**Pull request by TheDarkKnightRise**
```
setoption name NNUE value 0
NNUE is now set to false
go depth 18
time: -1 start: 185355750 stopOpt: 0 stopMax: 0 depth: 18 timeset: false nodeset: false
  1/1       0ms         0kn    +0.36      20kn/s g1f3
  2/4       0ms         0kn     0.00     109kn/s g1f3 g8f6
  3/5       0ms         0kn    +0.35     352kn/s g1f3 g8f6 d2d4
  4/8       0ms         1kn     0.00    1053kn/s g1f3 g8f6 d2d4 d7d5
  5/8      15ms         1kn    +0.33     110kn/s g1f3 g8f6 d2d4 d7d5 b1c3
  6/14     15ms         6kn     0.00     424kn/s g1f3 g8f6 d2d4 d7d5 b1c3 b8c6
  7/14     15ms         9kn    +0.28     650kn/s g1f3 g8f6 d2d4 d7d5 b1c3 b8c6 c1e3
  8/15     15ms        17kn    +0.08    1162kn/s b1c3 b8c6 e2e4 g8f6 d2d4 e7e5 g1f3 f8d6
  9/19     31ms        27kn    +0.14     874kn/s b1c3 b8c6 e2e4 e7e6 g1f3 d7d5 d2d4 g8f6
 10/19     78ms        77kn    +0.02     993kn/s b1c3 d7d5 d2d4 b8c6 g1f3 g8f6 c1e3 c8f5 a1c1 a8c8
 11/22    125ms       128kn    +0.22    1024kn/s g1f3 d7d5 d2d4 g8f6 b1c3 e7e6 c1g5 f8b4 g5f6 b4c3 b2c3 d8f6
 12/23    187ms       186kn    +0.20     997kn/s g1f3 d7d5 e2e3 g8f6 b1c3 b8c6 d2d4 e7e6 f1b5 f8d6 b5c6 b7c6 e1g1
 13/24    250ms       255kn    +0.14    1021kn/s g1f3 d7d5 e2e3 g8f6 b1c3 b8c6 d2d4 e7e6 f1d3 f8d6 e1g1 e8g8 e3e4
 14/27    437ms       476kn    +0.09    1089kn/s g1f3 d7d5 d2d4 g8f6 c1f4 e7e6 e2e3 f8d6 f4d6 c7d6 f1b5 b8c6 e1g1 e8g8 b1c3
 15/28    593ms       636kn    +0.20    1073kn/s g1f3 g8f6 d2d4 e7e6 b1c3 d7d5 e2e3 b8c6 f1d3 f8d6 e1g1 e8g8 e3e4 c6b4 c1e3
 16/31    1.11s      1197kn    +0.10    1079kn/s g1f3 g8f6 d2d4 e7e6 b1c3 d7d5 e2e3 b8c6 f1d3 f8b4 c1d2 e8g8 e1g1 c8d7 a1c1 a8c8
 17/31    1.36s      1480kn    +0.15    1089kn/s g1f3 g8f6 d2d4 e7e6 b1c3 d7d5 e2e3 b8c6 f1d3 c8d7 e1g1 f8d6 e3e4 d5e4 c3e4 e8g8
 18/32    2.09s      2284kn    +0.13    1091kn/s g1f3 g8f6 d2d4 e7e6 e2e3 f8e7 b1c3 e8g8 f1d3 d7d5 c1d2 b8c6 a1c1 c8d7 e1g1 a8c8 f3e5 c6e5
bestmove g1f3

```

### CODE REVIEW

**Comment by PGG106** [comment]
HCE was removed in https://github.com/PGG106/Alexandria/commit/856720a94061c26fb0e30a0a839b8dc3b1cd5309, that wasn't a mistake, this adds back in for no particularly good reason, i get that you want to contribute but do not make PRs that don't make sense, i removed it, if i wanted it in i wouldn't have removed it in the first place.

**Comment by PGG106** [comment]
If you submit any more nonsense PRs i will be forced to exclude you from the project. If you aren't sure about how to make meaningful contributions to the project know that you aren't forced to contribute to it. If you want to learn more about engine development i'd suggest developing one of your own.

**Comment by TheDarkKnightRise** [comment]
‏

**Comment by PGG106** [comment]
your last comment appeared as empty, i deleted it

**Comment by PGG106** [comment]
your comments showed up as a blank, i tried to edit it to see if i could read it but i accidentally deleted it

**Comment by TheDarkKnightRise** [comment]
You filled my path full of doubt
And wouldn't hear me out
But still I chased my dreams
You told me to quit
But my heart could not resist
And from the darkness came a light

**Comment by PGG106** [comment]
Lol what

**Comment by PGG106** [comment]
any change to search or eval (or that changes bench) has to go through a sprt test and is only merged if it passes, refer to the contribution guidelines for any question of this kind

**Comment by TheDarkKnightRise** [comment]
```
  1/3       0ms         0kn    +9.27      37kn/s f3f8 e8d7
  2/5      16ms         0kn    +9.05       6kn/s f3f8 e8d7 f8g8
  3/6      16ms         0kn    +6.59      45kn/s f3f8 e8d7 f8f7 d7d8 f7g7
  4/7      16ms         0kn    +6.89      54kn/s f3f8 e8d7 f8g8 d7c7 g8f8
  5/10     16ms         2kn    +5.87     167kn/s f3f8 e8d7 e3f3 d7c7 f8f7 c7b8 f3g3
  6/10     16ms         5kn    +5.30     356kn/s f3f2 e8d8 e3d3 d8c7 d3e3
  7/13     32ms        13kn    +4.59     422kn/s f3f8 e8d7 f8b8 d7c7 b8a8 e1c1 a8h8
  8/16     63ms        51kn    +3.85     814kn/s f3f8 e8d7 f8f6 d7c7 f6f4 e1c1 f4f7 c7b8 f7f8 b8a7 e3f3
  9/16     79ms        76kn    +3.88     973kn/s f3f8 e8d7 e3f3 d7c7 f8e8 e1a1 e8e2 a1f6 f3g3 f1a1 e2e8
 10/20    110ms       110kn    +3.71    1004kn/s f3f8 e8d7 f8e8 d7c7 e3f3 e1a1 e8e2 a1f6 f3g3 f1a1 e2d2 f6e5 g3h3
```

```
  1/3       0ms         0kn   -50.25      43kn/s f3f8 e8f8
  2/4       0ms         0kn   -53.66     198kn/s f3f7 d2d1q
  3/4       0ms         0kn   -53.73     265kn/s f3f7 d2d1q f7c7
  4/9       0ms         0kn   -53.68     693kn/s f3g3 d2d1q g3g8 e8f7 g8h8
  5/10     16ms         1kn   -53.69      73kn/s f3h3 d2d1q h3h8 e8f7 h8h7 f7g8 h7e7
  6/14     16ms         7kn   -54.13     492kn/s e3f4 d2d1q f3e3 e8f7 f4g3 d1d6 g3f3 f7g8
  7/14     16ms         8kn   -54.05     536kn/s e3f4 d2d1q f3e3 e8f7 f4g3 d1d6 g3f3 d6f6 f3g3 f7g8
  8/19     31ms        27kn   -58.82     880kn/s e3f4 d2d1q f4g3 d1d6 g3h3 d6e6 h3g3 e1b4 f3f4 e6g6 g3h3 b4c3 f4f3
  9/20     47ms        39kn   -58.82     841kn/s e3f4 d2d1q f4g3 d1d6 g3h3 d6e6 h3g3 e1b4 f3f4 e6g6 g3h3 b4c3 f4f3
 10/25    125ms       139kn   -62.88    1116kn/s e3e4 e1b1 e4f4 e2e1q f3e3 e8f7 e3e5 d2d1q e5f5 f7g6 f5g5 g6h7 g5f5
```

i want from @tissatussa to compare this

**Comment by PGG106** [comment]
you can ask them to do whatever you want, any change to search/eval has to go through SPRT as it is the case for every chess engine out there

**Comment by tissatussa** [comment]
i see no point to join this discussion .. i'm looking forward to a Classic Eval, this will be a first version anyhow.

**Comment by TheDarkKnightRise** [comment]
> i'm looking forward to a Classic Eval, this will be a first version anyhow.

Thanks for support

**Comment by PGG106** [comment]
a classical eval is present in any released version of alexandria up to 3.0.1 iirc, it's been removed because it was subpar and i don't plan on working on it anymore, a commit that simply undos me removing that isn't useful nor relevant, the end.

**Pull request closed without merging**
